############################################################
# Base Configuration
############################################################

# datasource base config 
spring.datasource:
  url: jdbc:postgresql://localhost:7336/gameShare
  username: gameShareCzar

# ORM base config
spring.jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect  
  database: POSTGRESQL
  hibernate:
    use-new-id-generator-mappings: true

# ActiveMQ base config
spring.activemq:
  pool.enabled: true

# JTA transaction base config
spring.jta.bitronix:
  # JTA ActiveMQ broker transaction base config
  connectionfactory:
    max-pool-size: 180
    min-pool-size: 4
    share-transaction-connections: true
    unique-name: amqConnectionFactory
    allow-local-transactions: false
    
  # JTA datasource transaction base config
  datasource:
    max-pool-size: 180
    min-pool-size: 4
    share-transaction-connections: true
    unique-name: gameSharePgSource
    isolation-level: REPEATABLE_READ

# Specify Active Configuration Profile    
spring:
  profiles.active: development
  
---

############################################################
# development Configuration Profile
############################################################

spring:
  profiles: development
  
spring.datasource:
  password: gameShareCzar
  
spring.jpa:
  show-sql: true
  hibernate:
    ddl-auto: create-drop

spring.activemq:
  broker-url: tcp://localhost:61616?daemon=true

---

############################################################
# production Configuration Profile
# Note that this requires pbe profile be activated as well
# (since ENC data is used)
############################################################

spring:
  profiles: production
  
security.require-ssl: true

spring.datasource:
  password: ENC(PC/xeyovY7zy7pXRL2OTXN86rNDAcT9ZHJkaGlF6Ju4yOdh9liNSXXrG+d6LRNv5fAQAb9LrO9mX7k19XIowDomECIJHuQoTlqvyIjFkPRg=)

spring.activemq:
  broker-url: ssl://10.1.100.55:61619?daemon=true
  user: uwebsvc
  password: ENC(8yEWKKBLo9ckUpnAadyolnROJoEQh9wb29N34ja9kFZekg0XsXLF2JqAfwyypzHUOhgpb63jvKBHZC0fEb2CpNQP/kYezS7C/9r0BHEYBOA=)

spring.jta.bitronix:
  connectionfactory:
    user: uwebsvc
    password: ENC(rjisNEwsRqA64SJ4hduy/rYlC4XhABAdrYI/mKGKmnALjjeNpH9kv5exslezYNGxjRI97K+OxYtFbkLXEoTZnXCqwU3tkHr9BqQSZ91F878=)