// <auto-generated />
namespace CastleHillGaming.Hms.DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DynamicMetrics : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DynamicMetrics));
        
        string IMigrationMetadata.Id
        {
            get { return "201905171752058_DynamicMetrics"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
