//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CastleHillGaming.Hms.DataModel.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("uAz9blJ3qK21QcWElLTCmqdeQT7Qhd5q3CBR7OWuJRvgwTx5eE4bXgHszj1Nozw")]
        public string EventEntityHashKey {
            get {
                return ((string)(this["EventEntityHashKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mUxBWFYonwhPeFYjl5zuIQt3oShOtxRF4FgAOAX7kz88dgNN6VtuTPoZjVtqIkd")]
        public string MeterEntityHashKey {
            get {
                return ((string)(this["MeterEntityHashKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wpaWQo88ZG4s4xIYRSGei3CxWEhkV8BLsosto0A5YdIHK1zocU681uHPsfOyeWN")]
        public string MetricEntityHashKey {
            get {
                return ((string)(this["MetricEntityHashKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("nB3v4MSTe61TgHrGrmgpnPwCDA1N9HYRxJ3snhha21loKiuWiMOnvMpg3NaVXce")]
        public string WindowsEventEntityHashKey {
            get {
                return ((string)(this["WindowsEventEntityHashKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("nKxe1EktUSZoOmTm4CYjr8eXx4bAUxRDzTDOo57SsJhmTTwTgcjMokLJ83nbsho")]
        public string VersionEntityHashKey {
            get {
                return ((string)(this["VersionEntityHashKey"]));
            }
        }
    }
}
